# Generated by Django 5.0.3 on 2024-04-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='hub',
        ),
    ]
